In [1]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print(torch.__version__)

c:\Users\leeki\anaconda3\envs\yolo\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


1.13.1+cpu


In [2]:
print('Hello World, Hi I\'m dlrlseong')

Hello World, Hi I'm dlrlseong


In [3]:
# Create a random tensor of size (3, 4)

random_tensor = torch.rand(1, 3, 4)
random_tensor

tensor([[[0.3879, 0.9925, 0.7482, 0.2428],
         [0.4128, 0.9427, 0.3846, 0.7132],
         [0.8243, 0.4545, 0.9193, 0.2228]]])

In [4]:
random_tensor.ndim

3

In [5]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) # height, width, color channels
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [6]:
random_tensor = torch.rand(224, 224, 3)
random_tensor.shape, random_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [7]:
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [8]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # what datatype is the tensor (e.g. float 32 or float16)
                               device=None, # what device is your tensor on
                               requires_grad=False) # whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [9]:
float_32_tensor.dtype

torch.float32

In [10]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [11]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [12]:
int_32_tensor = torch.tensor([3, 6, 9],
                             dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [13]:
# Create Tensor

some_tensor = torch.rand(3,3)
some_tensor

tensor([[0.4865, 0.5840, 0.8830],
        [0.2186, 0.6295, 0.5128],
        [0.5769, 0.8161, 0.0291]])

In [14]:
# Find out detail of tensor

print(some_tensor)
print(f'Datatype of tensor: {some_tensor.dtype}')
print(f'Shape of tensor: {some_tensor.shape}')
print(f'Device of tensor: {some_tensor.device}')

tensor([[0.4865, 0.5840, 0.8830],
        [0.2186, 0.6295, 0.5128],
        [0.5769, 0.8161, 0.0291]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 3])
Device of tensor: cpu


In [15]:
# Create a tensor add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [16]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [17]:
tensor

tensor([1, 2, 3])

In [18]:
# Substract 10
tensor - 10

tensor([-9, -8, -7])

In [19]:
# Try out PyTorch in-built function
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [20]:
# Element wise multiplication
print(tensor, '*', tensor)
print(f"Equals: {tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [21]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [22]:
# Matrix muliplication by hand

1*1 + 2*2 + 3*3

14

In [23]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: total: 0 ns
Wall time: 7.5 ms


In [24]:
%%time
torch.matmul(tensor, tensor)

CPU times: total: 0 ns
Wall time: 0 ns


tensor(14)

In [25]:
# The inner dimensions must match :

# torch.matmul(torch.rand(2, 3), torch.rand(2, 3)) // error
torch.matmul(torch.rand(2, 3), torch.rand(3, 2))

tensor([[0.9269, 0.3740],
        [0.3581, 0.2066]])

In [26]:
# The resulting matrix has the shape of the outer dimensions :

torch.matmul(torch.rand(10, 3), torch.rand(3, 10)).shape

torch.Size([10, 10])

# One of the most common errors in deep learning: shape errors

In [27]:
# Shapes for matrix multiplication

tensor_A = torch.tensor([[1, 2],
                        [3, 4],
                        [5, 6]])

tensor_B = torch.tensor([[7, 10],
                        [8, 11],
                        [9, 12]])

# torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul (it's an alias for writing less code)
torch.mm(tensor_A, tensor_B).shape

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [28]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix out tensor shape issue, we can manipulate the shape of one of our tensors using a **transpose**

A **transpose** switches the axes or dimensions of a given tensor

In [29]:
tensor_B, tensor_B.size()

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [30]:
tensor_B.T, tensor_B.T.size()

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [31]:
torch.mm(tensor_A, tensor_B.T).shape

torch.Size([3, 3])

# Finding the min, max, mean, sum, etc(tensor aggregation)

In [32]:
# Create a Tensor

x = torch.arange(1, 100, 10)
x, x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [33]:
# Find the min
torch.min(x), x.min()

(tensor(1), tensor(1))

In [34]:
# Find the max
torch.max(x), x.max()

(tensor(91), tensor(91))

In [35]:
# Find the mean
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [36]:
# Find the position in tensor that has the minimum value with argmin()
x.argmin()

tensor(0)

In [37]:
x[0]

tensor(1)

In [38]:
# Find the position in tensor that has the maximum value with argmax()
x.argmax()

tensor(9)

In [39]:
x[9]

tensor(91)

## Reshaping, stacking, squeezing and unsqueezing tensors


In [40]:
# Let's create a tensor
import torch
x = torch.arange(1., 11.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [41]:
# Add an extra dimension
x_reshaped = x.reshape(1, 10)
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [42]:
# torch.squeeze() - removes all single dimesions from a target tensor

x_reshaped.shape

torch.Size([1, 10])

In [43]:
x_reshaped.squeeze()

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [44]:
x_reshaped.squeeze().shape

torch.Size([10])

In [45]:
x_squeezed = x_reshaped.squeeze()
x_squeezed

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [46]:
x_squeezed.unsqueeze(dim=0)

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

In [47]:
# torch.permute - reaaranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224, 224, 3)) # [height, width, colour_channels]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")


Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


# Tensor Indexing

In [48]:
# Create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [49]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [50]:
# Let's index on the middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [51]:
# Let's index on the most inner bracket (last dimension)
x[0][0][0]

tensor(1)

In [52]:
x[0][2][2]

tensor(9)

In [53]:
# You can also use ":" to select "all" of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [54]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [55]:
x[:, 1, 1]

tensor([5])

In [56]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [57]:
x[0, 2, 2]

tensor(9)

In [58]:
x[:,:,2]

tensor([[3, 6, 9]])

## PyTorch tensors & Numpy

Numpy is popular scientific Python numerical computing library.

And because of this, PyTorch has functionality to interact with it.

* Data in Numpy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [59]:
# NumPy array to tensor

import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [60]:
array.dtype, tensor.dtype

(dtype('float64'), torch.float64)

In [61]:
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [62]:
# Tensor to Numpy array

tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [63]:
torch.rand(3, 3)

tensor([[0.4576, 0.9415, 0.4753],
        [0.3142, 0.8621, 0.2079],
        [0.1980, 0.1209, 0.6276]])

In [64]:
import torch

# Create two trandom tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.3453, 0.8063, 0.5617, 0.6613],
        [0.3185, 0.1888, 0.5723, 0.2585],
        [0.9346, 0.2670, 0.7089, 0.3438]])
tensor([[0.1770, 0.1260, 0.7406, 0.2635],
        [0.9774, 0.4858, 0.6244, 0.1792],
        [0.0453, 0.5168, 0.1516, 0.3141]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [65]:
# Let's make some random but reproducible tensors
import torch

# Set the random seed
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)


tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [66]:
# Check for GPU access with PyTorch
import torch
torch.cuda.is_available()

False

In [67]:
!nvidia-smi

Thu Mar  2 16:37:07 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 528.49       Driver Version: 528.49       CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:01:00.0  On |                  N/A |
|  0%   51C    P8    27W / 300W |    813MiB / 11264MiB |     25%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [68]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [69]:
# Count number of devices
torch.cuda.device_count()

0

In [70]:
# Create a tensor (default on the CPU)
tensor = torch. tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [71]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3])

In [72]:
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3], dtype=int64)

In [73]:
tensor_on_gpu

tensor([1, 2, 3])